---
# tasks file for web
- name: Instalar Apache2
  apt: 
    name: apache2 
    state: present

- name: Configurar pagina estatica
  template: 
    src: index.html.j2 
    dest: /var/www/html/index.html