---
# tasks file for router
- name: Eliminar nftables
  apt:
    name: nftables
    state: absent
  become: true

- name: Instalar iptables
  apt:
    name: iptables
    state: present
  become: true

- name: Habilitar enrutamiento IP
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Habilitar masquerade iptables
  iptables:
    table: nat
    chain: POSTROUTING
    source: 10.0.0.0/24
    out_interface: eth1
    jump: MASQUERADE

- name: Redirigir puerto 80
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth1
    protocol: tcp
    destination_port: 80
    jump: DNAT
    to_destination: "10.0.0.2:80"

- name: Eliminar ruta por defecto
  command: ip route del default

- name: Agregar ruta por defecto
  command: ip route add default via 192.168.15.1